### ISSUE TITLE
Simulation freezes when running with ClusteredLTS = 2

### ISSUE THREAD

**Issue by Yonatan298** [SeisSol/SeisSol#708] opened 2022-10-23 23:14 UTC
Hi, 
I am encountering a strange bug and would appreciate your help.
When running one of Ramos et al. 2021 simulations of Cascadia with ClusteredLTS = 2 (originally ran fine for Ramos et al. 2021), the code freezes, and the simulation doesn't proceed (the error at the end due to time out):
<img width="624" alt="Screen Shot 2022-10-23 at 3 13 32 PM" src="https://user-images.githubusercontent.com/107554177/197421163-37dcff0c-c124-4449-b39f-dad4b595f217.png">
(Also attached are the .err and .out files). The code works fine when using ClusteredLTS = 1. 

**Expected behavior**
Expected the simulation to run with ClusteredLTS = 2 as it does using ClusteredLTS = 1.

**To Reproduce**
I linked my parameters: par, SeiSsol executable, and the mesh file. Next, run the run_seisol_test.sh file using the attached parameters and input files.

I am running the simulations on the new project pn49ha, using the SeiSsol from the installed seissol-env by Nico Schliwa:
module use /hppfs/work/pn49ha/ru76tuj2/modules/linux-sles15-skylake_avx512/
module load seissol-env/develop-intel21-impi-x2b 
Not sure what version I am using (I think it is the CPU version). 

Provided files:
Output files from the simulation with ClusteredLTS = 2:
[ClusteredLTS = 2_id_2398438_result.err.txt](https://github.com/SeisSol/SeisSol/files/9847680/ClusteredLTS.2_id_2398438_result.err.txt)
[ClusteredLTS = 2_id_2398438_result.out.txt](https://github.com/SeisSol/SeisSol/files/9847681/ClusteredLTS.2_id_2398438_result.out.txt)
The output file from the simulation with ClusteredLTS = 1:
[ClusteredLTS = 1.result.out.txt](https://github.com/SeisSol/SeisSol/files/9847683/ClusteredLTS.1.result.out.txt)
Files to run/reproduce the simulation:
[parameters.par.txt](https://github.com/SeisSol/SeisSol/files/9847686/parameters.par.txt)
[run_seisol_test.sh.txt](https://github.com/SeisSol/SeisSol/files/9847687/run_seisol_test.sh.txt)
[CasSlab2-2500.zip](https://github.com/SeisSol/SeisSol/files/9847692/CasSlab2-2500.zip)
[input_files.zip](https://github.com/SeisSol/SeisSol/files/9847701/input_files.zip).

P.S
Working on trying the coarser mesh of Cascadia from /hppfs/work/pn49ha/di73yeq4/cascadia:
[cascadia60_coarse.msh.txt](https://github.com/SeisSol/SeisSol/files/9847723/cascadia60_coarse.msh.txt). However, I need first to convert it to hd5 format (not sure I can do that on the SuperMUC-NG).

Thanks in advance, and please let me know if anything further is needed.

**Comment by Thomas-Ulrich** [comment] 2022-10-24 06:27
Hi,
Please try with:
```
&Output
(...)
xdmfWriterBackend = 'posix' ! (optional) The backend used in fault, wavefield,
! and free-surface output. The HDF5 backend is only supported when SeisSol is compiled with
! HDF5 support.
(...)
\
```

**Comment by Yonatan298** [comment] 2022-10-24 16:05
Hi Thomas,
Thank you for the suggestion. However, the problem didn't resolve.
I will appreciate any other suggestions
Provided files:
[2405469.result.out.txt](https://github.com/SeisSol/SeisSol/files/9853181/2405469.result.out.txt)
[parameters.par.txt](https://github.com/SeisSol/SeisSol/files/9853182/parameters.par.txt)

**Comment by Thomas-Ulrich** [comment] 2022-10-26 08:14
I try this setup (2 and 16 nodes), and it worked fine:
```/hppfs/work/pn49ha/di73yeq4/cascadia_fixed```

**Comment by Thomas-Ulrich** [comment] 2022-10-27 12:38
are you on pn49ha?
I did that, then it should work
```di73yeq4@login03:/hppfs/work/pn49ha/di73yeq4> chmod -R g+rX ../../pn49ha/di73yeq4/```

**Comment by Yonatan298** [comment] 2022-10-27 16:17
Hi Thomas,
Thanks for the suggestion. Yes, I am on pn49ha. Still getting permission denied:
<img width="569" alt="Screen Shot 2022-10-27 at 9 13 59 AM" src="https://user-images.githubusercontent.com/107554177/198343573-cd0cdd49-1de0-4961-982d-793125aeb33f.png">
[Terminal.txt](https://github.com/SeisSol/SeisSol/files/9881241/Terminal.txt)

**Comment by Thomas-Ulrich** [comment] 2022-10-27 16:45
I mean that s how I set up the permission. You do not need to run chmod but you should be able to cd, ls or read files in the directory. 

Le 27 octobre 2022 18:17:15 GMT+02:00, YonatanG ***@***.***> a écrit :

**Comment by Yonatan298** [comment] 2022-10-27 17:57
Hi Thomas,
I tried that already, but I am still getting permission denied:
<img width="573" alt="Screen Shot 2022-10-27 at 10 55 16 AM" src="https://user-images.githubusercontent.com/107554177/198363810-759c966c-087b-4c0c-8b96-b293fb4f4cc4.png">

**Comment by AliceGabriel** [comment] 2022-10-27 18:39
@Thomas-Ulrich thanks a lot for helping, could you let @Yonatan298 know what you fixed (does not have to be here) but for future cases

**Comment by Yonatan298** [comment] 2022-10-27 19:10
Hi Thomas,
I checked the permissions, and it seems that pn49ha doesn't have access to the Cascadia_fixed folder.
 
<img width="573" alt="Screen Shot 2022-10-27 at 12 04 40 PM" src="https://user-images.githubusercontent.com/107554177/198377009-84c83086-6433-418d-9037-cf14742e15fb.png">

Could you please allow access to this folder? And let me know what exactly you fixed to make it work.
Thanks again for all your help

**Comment by Thomas-Ulrich** [comment] 2022-10-28 06:21
Ok, I understand now, 
```
di73yeq4@login02:/hppfs/work/pn49ha/di73yeq4> ls -ltrd *
-rwxrwxrwx 1 di73yeq4 pr45fi-d 9952160 27. Jul 11:53 plastic-profile
drwxr-sr-x 4 di73yeq4 pn49ha-d    4096  6. Okt 17:01 kaikoura
drwxr-sr-x 2 di73yeq4 pn49ha-d    4096 13. Okt 21:41 cascadia
drwxr-s--- 3 di73yeq4 pr45fi-d    4096 26. Okt 10:11 cascadia_fixed
```
The user group associated with cascadia_fixed is pr45fi-d, not pn49ha-d as the other folders.
Anyway I change permission to all users for the folder now.

**Comment by Yonatan298** [comment] 2022-10-31 03:59
Hi Thomas,
Thank you so much for your help. I tried to run the files in /hppfs/work/pn49ha/di73yeq4/cascadia_fixed.
The simulation does not freeze. However, after about 13 minutes I get an error, and the simulation terminates. 
Could you please take a look at the attached files? Also, could you please highlight the modification you made to the original files? I saw that you changed the submission.sh file quite extensively (for example, assigning ntasks-per-node=2 instead of 1 or using module switch mpi.intel mpi.intel/2019 instead of module load slurm_setup). I hope it will help me better understand the source of the errors I am getting.

Provided files:
[2412742.result.err.txt](https://github.com/SeisSol/SeisSol/files/9897930/2412742.result.err.txt)
[2412742.result.out.txt](https://github.com/SeisSol/SeisSol/files/9897931/2412742.result.out.txt)
[parameters.par.txt](https://github.com/SeisSol/SeisSol/files/9897932/parameters.par.txt)
[submission.sh.txt](https://github.com/SeisSol/SeisSol/files/9897933/submission.sh.txt)

**Comment by Thomas-Ulrich** [comment] 2022-10-31 09:43
Hi,
This is because there is no more source on disk. Quotas on home are very tight, not the place to run write output. There should be more space on work but still limited. Scratch should be unlimited, but files are removed from now and then. 

Le 31 octobre 2022 04:59:26 GMT+01:00, YonatanG ***@***.***> a écrit :

**Comment by krenzland** [comment] 2023-02-28 09:50
I'm closing this issue as it seems like we cannot reproduce it.

**Closed by krenzland** 2023-02-28 09:50 UTC
Labels: bug
