### ISSUE TITLE
Assertion `ct.predictionTime > lastSendTime' failed (Alaska model)

### ISSUE THREAD

**Issue by daisy20170101** [SeisSol/SeisSol#777] opened 2023-01-19 05:34 UTC
**Describe the bug**

I run my Alaska model with the latest SeisSol, activating TP on the fault, which works well with the previous version e.g. thomas/optimize_TP. 

It failed after output at 0.0 with the warning and errors:

Thu Jan 19 06:19:57, Warn:  Found a negative state variable while initializing the fault. Are you sure your setup is correct?

SeisSol_Debug_dskx_2_elastic: /hppfs/work/pr63qo/di52lak2/easi_2019-11/SeisSol/src/Solver/time_stepping/GhostTimeCluster.cpp:26: void seissol::time_stepping::GhostTimeCluster::receiveGhostLayer(): Assertion `ct.predictionTime > lastSendTime' failed.
SeisSol_Debug_dskx_2_elastic: /hppfs/work/pr63qo/di52lak2/easi_2019-11/SeisSol/src/Solver/time_stepping/GhostTimeCluster.cpp:26: void seissol::time_stepping::GhostTimeCluster::receiveGhostLayer(): Assertion `ct.predictionTime > lastSendTime' failed.
SeisSol_Debug_dskx_2_elastic: /hppfs/work/pr63qo/di52lak2/easi_2019-11/SeisSol/src/Solver/time_stepping/GhostTimeCluster.cpp:26: void seissol::time_stepping::GhostTimeCluster::receiveGhostLayer(): Assertion `ct.predictionTime > lastSendTime' failed.

**Expected behavior**

Could you help to fix it?

**To Reproduce**

I used the following module on NG:
Currently Loaded Modulefiles:
 1) admin/1.0     4) spack/22.2.1                                     7) intel-mpi/2019-intel    10) libszip/2.1.1  13) python/3.8.11-extended                
 2) tempdir/1.0   5) intel-oneapi-compilers/2021.4.0(default:intel)   8) lrztools/2.0            11) gcc/11.2.0     14) slurm_setup/1.0                       
 3) lrz/1.0       6) intel-mkl/2020    9) numactl/2.0.14-intel21  12) cmake/3.21.4   15) seissol-env/develop-intel21-impi-x2b  

the folder is here:
/hppfs/work/pr63qo/di52lak2/AlaskaR057_finemesh/

Seissol version:
commit 4889c3a094f29bac3efbf430d13139cb04a701a3 (HEAD -> master, origin/master, origin/HEAD)
Merge: bdd6e5bb 3a3b1de1
Author: ravil-mobile <ravil.mobile.com@gmail.com>
Date:   Thu Jan 12 20:45:58 2023 +0100

    Merge pull request #766 from SeisSol/ravil/graphs
    
    Ravil/graphs

**Screenshots/Console output**
If you suspect a problem in the numerics/physics add a screenshot of your output.

If you encounter any errors/warnings/... during execution please provide the console output.

**Additional context**

**Comment by sebwolf-de** [comment] 2023-01-19 07:48
This seems to be a duplicate of #776, does it work, if you compile the `Release`  version?

**Comment by krenzland** [comment] 2023-01-20 16:29
Closed as duplicate of #776.

**Closed** 2023-01-20 16:29 UTC
Labels: bug
