### ISSUE TITLE
Inconsistent number of elements in the surface output 

### ISSUE THREAD

**Issue by Shihao-Yuan** [SeisSol/SeisSol#333] opened 2021-05-03 16:30 UTC
**Describe the bug**
I have performed a series of simulations with various point source locations under the same mesh. However, the total number of elements in each surface output slightly differ with each.

**Expected behavior**
I expect the total number of elements in the output remains the same when not altering the mesh file or any other related parameters.

**Comment by uphoffc** [comment] 2021-05-03 16:49
Initially I thought this is due to ghost cells, but now I recall that the bug is caused by duplicated cells in the LTS scheme (really something that should be abolished).

When looping over the elements one should identify whether a cell is a duplicate in
https://github.com/SeisSol/SeisSol/blob/master/src/Solver/FreeSurfaceIntegrator.cpp#L230
The check can be implemented with something like
lts == ltsId(meshId(lts))
or alternatively one iterates over the mesh ids.

@krenzland : Is there anything that would break in your elastic-acoustic output / coupling if the duplicated cells are removed?

**Comment by krenzland** [comment] 2021-05-03 18:01
No, I don't think it would break the coupling. It might break my new custom output (I don't think it would) but that's in a different branch so it doesn't matter.

**Comment by uphoffc** [comment] 2021-05-04 13:27
@Shihao-Yuan , can you confirm that the issue is fixed by branch carsten/fix-duplicate-surface-output?

**Comment by Shihao-Yuan** [comment] 2021-05-04 18:14
@uphoffc, I think the issue is fixed now. I have run 30 simulations and all surface output have the same number of elements. Thanks a lot.

**Comment by uphoffc** [comment] 2021-05-05 07:03
Great!

**Closed by uphoffc** 2021-05-05 07:03 UTC
Labels: bug
