### ISSUE TITLE
Error running SeisSol for first time: "initialization Gauss wise"

### ISSUE THREAD

**Issue by gmocornejos** [SeisSol/SeisSol#33] opened 2017-04-24 21:56 UTC
Hello!

I'm trying to run SeisSol on a small cluster with Intel Xeon Phi KNL nodes. I followed the instructions in [here](https://github.com/SeisSol/SeisSol/wiki/Compilation) and [here](https://github.com/SeisSol/SeisSol/wiki/First-run), _apparently_ I successfully installed  SeiSsol, but trying to run "First run" example I got some error about "initialization Gauss wise". In the attached zip you can find stderr, stdout, parameters file, and out put files, also PBS file.
[seissol-cenat.zip](https://github.com/SeisSol/SeisSol/files/953283/seissol-cenat.zip)

Thanks for your help,

**Comment by rettenbs** [comment] 2017-04-25 08:45
Hi,

the error message is not an error (we need to change this in the code).
Can you try to compile SeisSol with debug information (compileMode=relWithDebInfo)?

Best,

**Comment by gmocornejos** [comment] 2017-04-25 22:13
Sure! So, I went to `SeisSol/build/options/supermuc_mac_cluster.py` and changed `compileMode = release` to `compileMode = relWithDebInfo` , and then typed `scons -j 32 buildVariablesFile=build/options/supermuc_mac_cluster.py` , that was it, right? 

I got the following error message:

mpiifort -o build/SeisSol_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4 -nofor-main -cxxlib -xMIC-AVX512 -fma -DENABLE_MATRIX_PREFETCH -DENABLE_STREAM_MATRIX_PREFETCH -DNUMBER_OF_THREADS_PER_GLOBALDATA_COPY=4 -ip -ipo -g -rdynamic -fopenmp -Wl,-rpath=/home/gmocornejos/lib build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/src/seissolxx.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/src/SeisSol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/src/main.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Monitoring/bindMonitoring.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Monitoring/FlopCounter.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/GambitReader.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/read_mesh.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/compute_mesh_info.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/allocate_mesh.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/MeshReaderCBinding.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/MeshReaderFBinding.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/MeshTools.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Geometry/mpiextractmesh.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Kernels/TimeCommon.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/InternalState.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/MemoryAllocator.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/MemoryManager.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/time_stepping/LtsLayout.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/CellLocalMatrices.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/tree/Lut.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/ini_seissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/ini_optionalfields.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/dg_setup.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Initializer/ini_calcseissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/generated_code/matrix_kernels/sgemm_knl.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/generated_code/matrix_kernels/sparse_sknl.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/Kernels/Time.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/Kernels/Volume.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/Kernels/Boundary.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Equations/elastic/Model/Setup.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Model/common.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/Transformation.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/gauss.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/create_fault_rotationmatrix.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/typesdef.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/operators.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/convertxieta2xy.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/dgbasis.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/ini_quadfreedg.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/jacobinormal.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/quadpoints.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/sp_matmul.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Numerical_aux/trilinearinterpolation.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Physics/Evaluate_friction_law.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Physics/galerkin_source.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Physics/ini_model.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Physics/ini_model_DR.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Physics/initialfield.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/read_backgroundstress.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/readpar.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/readparC.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/faultinput.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/VelocityFieldReaderF.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Reader/VelocityFieldReaderC.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/analyse_seissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/inioutput_seissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/data_output.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/output_rupturefront.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/magnitude_output.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/energies.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/common_receiver.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/receiver.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/plot_fields.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/printthistimestep.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/common_fault_receiver.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/faultoutput.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/ini_faultoutput.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/WaveFieldWriterC.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/WaveFieldWriterF.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/WaveFieldWriter.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/FaultWriterC.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/FaultWriterF.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/ResultWriter/PostProcessor.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/f_ftoc_bind_interoperability.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/f_ctof_bind_interoperability.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/Interoperability.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/time_stepping/TimeCluster.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/time_stepping/TimeManager.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/Simulator.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/calc_seissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/close_seissol.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/calc_deltat.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/cauchykovalewski.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/friction.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/galerkin3d_solver.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/plasticity.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/prak_clif_mod.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Solver/mpiexchangevalues.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/SourceTerm/PointSource.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/SourceTerm/Manager.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/SourceTerm/NRFReader.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Parallel/MPI.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Parallel/mpiC.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Parallel/mpiF.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/Backend.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/Fault.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/Manager.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/posix/Fault.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/posix/Wavefield.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/h5/Fault.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/h5/Wavefield.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/mpio/Wavefield.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/mpio/WavefieldAsync.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/mpio/Fault.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/Checkpoint/mpio/FaultAsync.o build/build_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4/submodules/pugixml/src/pugixml.o -L/home/gmocornejos/lib -lhdf5_hl -lhdf5 -lz -ldl -lm -lnetcdf -lhdf5_hl -lhdf5 -lz -lcurl -ldl -lpthread
20000_0

fortcom: Severe: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.

ipo-2: error #11005: multi-object compilation 2 returned error status 3
ifort: error #10014: problem during multi-file optimization compilation (code 3)
scons: *** [build/SeisSol_relWithDebInfo_generatedKernels_sknl_hybrid_none_9_4] Error 3
scons: building terminated because of errors.

If I change compileMode back to release, it compiles normally and produces an executable.

**Comment by Thomas-Ulrich** [comment] 2017-04-25 22:26
Hi, 
I precise I m not from the TUM team, so I ve limited knowledge of the optimisations of the code and new implementations. 
Maybe you can try compiling in fully debug mode, using releasemode=Debug. 
Also maybe you can try checking out the branch drlts, which is the unofficially yet future master branch, and may be more bug free for knl. 
Thomas.

**Comment by rettenbs** [comment] 2017-04-28 14:11
Hi,

looks like the ipo is not working. It is not required and we already removed this flag in our development version. Can you remove these lines and try again: https://github.com/SeisSol/SeisSol/blob/master/site_scons/arch.py#L92

Additionally, you are using single precision. This is not well tested. Have you tested double precision (use dknl instead of sknl).

Best regards

**Comment by gmocornejos** [comment] 2017-05-02 17:37
Hello Tomas and Sebastian, 

Thank you very much for your help! To solve the problem, I changed to double precision (dknl) and commented lines 91 and 92 in SeisSol/site_scons/arch.py. It worked with compileMode in `debug` and `release`. 

Simulation outputs two "kind of signals", I suppose the ones that looks like these:
![tpv33-rf-00000-tid-00](https://cloud.githubusercontent.com/assets/4778547/25630280/cae798b4-2f29-11e7-9bc1-dd6bbf7d9219.png)
Are synthetic seismographs, but what are the others? like the following:
![tpv33-receiver-00083-00020](https://cloud.githubusercontent.com/assets/4778547/25630317/f3563648-2f29-11e7-9543-40445e60fb08.png)

Also, in stdout, I got the following message:

Mon May 01 04:41:34, Info:  #max-updates since sync:  46200  @  11.8827 
Mon May 01 04:42:29, Info:  #max-updates since sync:  46300  @  11.9085 
Mon May 01 04:43:23, Info:  #max-updates since sync:  46400  @  11.9342 
Mon May 01 04:44:18, Info:  #max-updates since sync:  46500  @  11.9599 
Mon May 01 04:45:13, Info:  #max-updates since sync:  46600  @  11.9856 
Rank:        0 | Info    | total number of performed time steps:            0
Rank:        0 | Info    | final time of the simulation:    12.0000000000000     

#===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 146286 RUNNING AT phi-d.cnca
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
#===================================================================================

Is that OK?

As you may remember, we are planing to run some simulations with volcanoes, do you think we should checkout to development branch? Thomas suggested it in order to solve the problem, but maybe it is a good idea, even with the problem solved.

**Comment by Thomas-Ulrich** [comment] 2017-05-03 08:09
tpv33-RF* files are the first arrival of the rupture front at each gauss point on the fault.
they contain x,y,z (coordinates of the gauss point), t (rupture time)
tpv33_receivers are synthetic seismograms (off fault receivers).

**Comment by swollherr** [comment] 2017-06-29 08:57
The master branch can still be used for your type of simulations.
We will merge a stable version of the newest features into the master branch soon.
If the problem is solved, I'm going to close this issue.

**Comment by gmocornejos** [comment] 2017-06-30 14:36
Ok! Thank you!

**Closed** 2017-06-30 14:37 UTC
