### ISSUE TITLE
tpv5 slip artifacts 

### ISSUE THREAD

**Issue by NicoSchlw** [SeisSol/SeisSol#546] opened 2022-05-10 10:33 UTC
**Describe the bug**
Tpv5 produces elements with unreasonable high absolute slip.

**Expected behavior**
A reasonable and smooth absolute slip distribution. 

**To Reproduce**
1. Which version do you use? d5656cd; but had the same problem also with 9895309
2. Which build settings do you use? Which compiler version do you use? Double precision, order 4
3. On which machine does your problem occur? If on a cluster: Which modules are loaded? I'm running it on Supermuc and compiled SeisSol following the documentation: https://seissol.readthedocs.io/en/latest/supermuc.html
![Screenshot from 2022-05-10 12-13-57](https://user-images.githubusercontent.com/42612980/167606151-0f0b1805-4081-4d9f-8c6d-4c35d41a5195.png)

4. Provide parameter/material files.

[parameters.txt](https://github.com/SeisSol/SeisSol/files/8660675/parameters.txt)

[2089910.tpv5.out.txt](https://github.com/SeisSol/SeisSol/files/8660677/2089910.tpv5.out.txt)

**Screenshots/Console output**
![Screenshot from 2022-05-09 20-05-08](https://user-images.githubusercontent.com/42612980/167604777-8671026b-fefd-4137-a613-671781ab162c.png)

If you encounter any errors/warnings/... during execution please provide the console output.
I got no errors.

**Additional context**
I used this setup: https://github.com/SeisSol/Examples/tree/master/tpv5
and increased the domain size and resolution (150m on-fault element size; order 4).

**Comment by Thomas-Ulrich** [comment] 2022-06-02 09:48
Hi,
I can confirm that it is not fixed by the new fault output. 
And it is not fixed by the new quadrature rule (see a comparison of P_n, top Dunavant, bottom strout.
![image](https://user-images.githubusercontent.com/13536910/171603329-6a00e074-e09e-42ac-b167-6020a14b2294.png)

The only know way to mitigate the problem are:
- use a symmetrical mesh (no more problem)
- modify an impedance, as in https://github.com/SeisSol/SeisSol/commit/181fc85d5c405a8c44fe21869fe736ab1f0206d5
(but this comes with a loss of accuracy).

**Comment by sebwolf-de** [comment] 2022-09-07 08:59
I would like to add some details: If I use the "eta-hack" from 181fc85 (blue) and compare it to the master (orange), I first see the initial rupture (until ~1s), which then comes to stop. For the master I see slow-slip rupture after ~2s until ~8s. The plateau between 8s and 10s indicates that this is not a numerical instability (or at least not the kind of instability that blows up to infinity). I also checked until 40s. The solution stays constant after ~10s.
The solution (P_n = 20GPa, T_s = 0, |SR| ~= 2.55m/s) seems to be a stable solution of the friction problem. 
![Receiver_1](https://user-images.githubusercontent.com/24592027/188837006-73545147-1195-451a-b7a1-c61015077955.png)
Unfortunately, there are several such solutions, see the second screenshot (only 150m distance between both receivers).
![Receiver_2](https://user-images.githubusercontent.com/24592027/188837031-c296f498-0f16-47bb-b54c-cd790de83d19.png)

**Comment by Thomas-Ulrich** [comment] 2022-09-07 10:50
I guess the question is what generates locally normal stress, on the master branch.

**Comment by sebwolf-de** [comment] 2022-09-07 11:50
Interstingly, if we increase the output subsampling, we see that only a few elements (gauss-poitns) are bugged.
Top: master, Bottom: "eta-hack"
![Screenshot from 2022-09-07 13-49-29](https://user-images.githubusercontent.com/24592027/188871548-06c15e58-1c3a-4f9b-8023-dffabe35d5f1.png)

**Comment by sebwolf-de** [comment] 2022-09-07 11:53
I also put 64 faultreceivers into one single fault element and found that within one element, we find qualitatively completely different solutions.

**Comment by Thomas-Ulrich** [comment] 2022-09-07 12:34
What may complicate the investigation is the resampling of the state variable which blurs the pattern within each cell.
if you turn that off, you will probably see that the anomalies are on totally isolated GP.
I would rather look at Pn0 (unaffected by the friction law, rather than Ts0, which is updated by the friction law).

**Comment by sebwolf-de** [comment] 2022-09-07 13:07
Unfortunately, omitting the filter, does not help. But it was a good idea, thanks!
Without the filtering, I still see different variants within this one cell. For one GP, Pn0 drops from -1.2e8 to -1.8e8 and for another one, Pn0 rises from -1.2e8 to -0.6e8.

**Comment by sebwolf-de** [comment] 2022-09-07 14:37
The more I think about it, the more inclined I am to believe it is some kind of numerical artifact, e.g. cancelation in https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h#L74-L76

**Comment by sebwolf-de** [comment] 2022-09-09 10:37
I created a coarse symmetric mesh and then moved one node by 20m (element size ~200m in that region) and I could reproduce a faulty behaviour :/

**Comment by sebwolf-de** [comment] 2022-09-09 13:10
Top: Almost symmetric mesh, with one node moved, Bottom: symmetric mesh. Note the different scales for top and bottom.
![Screenshot from 2022-09-09 15-09-28](https://user-images.githubusercontent.com/24592027/189357455-b33eda79-5115-4efe-94fe-f88c20bf61aa.png)

**Comment by sebwolf-de** [comment] 2022-09-09 13:12
You can find the meshes here: https://syncandshare.lrz.de/getlink/fiKLV98vp9x3J7BpSYiFDv/TPV5-issue-546

**Comment by daisy20170101** [comment] 2023-05-09 09:44
Hi, I recently have this issue with my application. I am wondering where could I add this 'eta-hack' to fix it temporally.  Thanks!

**Comment by francescomosconi** [comment] 2024-01-23 14:20
Hello,

I'm encountering the same slip artifacts on a 70° dipping fault. I also observe a strong oscillation in normal stress in the receivers (see attached image). Could you provide more details on how to temporarily fix this behavior with the above-mentioned "eta-hack"? I am currently working with GPUs; should it work correctly like this as well?

Many thanks in advance!

![fault_rec_51](https://github.com/SeisSol/SeisSol/assets/84501864/d60e0875-b038-4eba-91e6-30144c5178f2)

**Comment by davschneller** [comment] 2024-04-03 10:15
Apologies for the large delay—we've added the "eta hack" as a parameter now to the main branch (cf. #1087 ). I.e. if you specify `etahack=0.9` in the `dynamicrupture` section, you should enable it (the default value is `etahack=1`). Also, it should work on GPUs.

**Comment by Thomas-Ulrich** [comment] 2024-10-07 06:25
fixed by https://github.com/SeisSol/SeisSol/pull/1176 
(adding
```
numflux = 'rusanov' ! The numerical flux. Values: 'godunov', 'rusanov'
numfluxnearfault = 'rusanov' ! The numerical flux for faces of cells adjacent to the fault (on cells which have at least one DR face), excluding the DR faces themselves. Values: 'godunov', 'rusanov'
```
to equations.

**Closed by Thomas-Ulrich** 2024-10-07 06:25 UTC
Labels: bug
