### ISSUE TITLE
Deterministic mesh partitioning

### ISSUE THREAD

**Issue by jrekoske** [SeisSol/SeisSol#427] opened 2021-11-18 21:12 UTC
When running identical jobs (same mesh and number of MPI ranks), I noticed that the partitions are different. This is undesirable for certain post-processing activities. 

I read the parmetis manual (http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/manual.pdf) and all the parmetis API’s accept an option[] array. It appears that option[2] specifies the seed used to generate a partition.

From page 24:
 options This is an array of integers that is used to pass additional parameters for the routine. The first element
(i.e., options[0]) can take either the value of 0 or 1. If it is 0, then the default values are used,
otherwise the remaining three elements of options are interpreted as follows:

options[2] This is the random number seed for the routine.

So it would appear that fixing the value of option[2] = XXX would solve the non-deterministic partition problem.

Does anyone foresee any problems with fixing the seed for all simulations?

**Comment by jrekoske** [comment] 2021-11-18 21:31
It seems like a simple fix to change this line 

https://github.com/TUM-I5/PUML2/blob/57bfa7df18ab3610e66a5827a64dca6b28bd168b/PartitionMetis.h#L139

to idx_t options[3] = {1, 1, 0}

**Comment by krenzland** [comment] 2021-11-18 21:34
METIS_RANDOM_SEED is a constant already (defined in the same file), so the metis call itself should be deterministic.
There is also the compile option -DMINI_SEISSOL=OFF which sets the weights of all nodes to 1 (instead of varying weights). Note that this will likely lead to a loss of performance for large runs.

Why is the inconsistent mesh partitioning a problem for your use case?

**Comment by AliceGabriel** [comment] 2021-11-18 22:46
Hi, we here really need to have consistent element ids across many simulations using the same mesh. The simulations are not large.

**Comment by krenzland** [comment] 2021-11-18 23:03
Sure, but it is quite easy to reorder elements in post-processing, especially for small simulations. You can steal the logic from here:  https://github.com/SeisSol/SeisSol/blob/master/postprocessing/science/compute_diff_seissol_data.py

In any case, I believe that -DMINI_SEISSOL=OFF should lead to deterministic partitioning.

**Comment by ravil-mobile** [comment] 2021-11-19 10:07
I can confirm that by configuring SeisSol with `-DMINI_SEISSOL=OFF` is going to solve the problem.

**Comment by Thomas-Ulrich** [comment] 2021-11-19 12:39
good to know. Maybe we can document this idea and close the issue?

**Comment by krenzland** [comment] 2021-11-19 14:38
It is not documented for a reason - I am not sure that this actually solves the mesh reordering issue and because it incurs a severe performance penalty on some machines. It is in general not a good idea to use this. The main reason it exists is because in our SC21 paper we explicitly state that MINI_SEISSOL is an optimization that is crucial for good performance - and we needed a baseline to compare against.

**Comment by ravil-mobile** [comment] 2021-12-09 15:16
I guess it is good to document in case somebody wants to do debugging

**Comment by davschneller** [comment] 2023-12-08 12:08
Mini_SeisSol can be toggled since #986 (and that option is documented). I'll close this issue for now—feel free to re-open if the issue re-appears.

**Closed by davschneller** 2023-12-08 12:08 UTC
