### ISSUE TITLE
PUML::Distributor::localToGlobalId(unsigned long, unsigned long): Assertion localId < size failed

### ISSUE THREAD

**Issue by fabian-kutschera** [SeisSol/SeisSol#786] opened 2023-02-03 10:37 UTC
**Describe the bug**
When I run a dynamic rupture simulation (on the test partition with 16 nodes, but also on general with 64 nodes) which gets informed by the stress change of a kinematic simulation I get a Segmentation fault after the XDMF fault output is initialized.

The *.out file gives:

> Fri Feb 03 11:27:48, Info:  Welcome to SeisSol 
> Fri Feb 03 11:27:48, Info:  Copyright (c) 2012-2021, SeisSol Group 
> Fri Feb 03 11:27:48, Info:  Built on: Nov 30 2022 17:14:18 
> Fri Feb 03 11:27:48, Info:  Version: 202103_Sumatra-1139-g00bbf63e 
> Fri Feb 03 11:27:48, Info:  Running on: i01r01c02s05 
> Fri Feb 03 11:27:48, Info:  Using MPI with #ranks: 16 
> Fri Feb 03 11:27:48, Info:  Using OMP with #threads/rank: 94 
> Fri Feb 03 11:27:48, Info:  OpenMP worker affinity (this process): "0123456789|0123456789|0123456789|0123456789|0123456-89|0123456789|0123456789|0123456789|0123456789|01234-" 
> Fri Feb 03 11:27:48, Info:  OpenMP worker affinity (this node)   : "0123456789|0123456789|0123456789|0123456789|0123456-89|0123456789|0123456789|0123456789|0123456789|01234-" 
> Fri Feb 03 11:27:48, Info:  Communication thread affinity        : "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5" 
> Fri Feb 03 11:27:48, Info:  The stack size ulimit is  2097152 [kb]. 
> Fri Feb 03 11:27:48, Info:  Input Parameters:
>  0x143a9c0 
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <                SeisSol MPI initialization               >
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    |  Double precision used for real.
> Rank:        0 | Info    | <--------------------------------------------------------->
>  INFORMATION: The assumed unit number is           6 for stdout and           0 
>  for stderr.
>               If no information follows, please change the value.
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <     Start ini_SeisSol ...                               >
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <  Parameters read from file: parameters_samos_noWL.par              >
> Rank:        0 | Info    | <                                                         >
> Rank:        0 | Info    | No plasticity assumed. 
> Rank:        0 | Info    | No attenuation assumed. 
> Rank:        0 | Info    | No adjoint wavefield generated. 
> Rank:        0 | Info    | Isotropic material is assumed. 
> Rank:        0 | Info    | Read a PUML mesh file
> Rank:        0 | Warning | Ignoring space order from parameter file, using           4
> Rank:        0 | Info    | Volume output is disabled
> Rank:        0 | Info    | Use HDF5 XdmfWriter backend
> Rank:        0 | Info    | Refinement for volume output is disabled
> Fri Feb 03 11:27:48, Info:  Running mini SeisSol to determine node weight 
> Fri Feb 03 11:27:48, Info:  Node weights: mean = 39.3856  std = 0.724634  min = 36.7405  median = 39.6132  max = 39.8704 
> Fri Feb 03 11:27:48, Info:  Reading PUML mesh mesh_noWL_Samos_Fra 
> Fri Feb 03 11:27:48, Info:  Found 12276784 cells 
> Fri Feb 03 11:27:48, Info:  Found 2403223 vertices 
> Fri Feb 03 11:28:05, Info:  Computing LTS weights. 
> Fri Feb 03 11:28:17, Info:  Computing LTS weights. Done.  (44233 reductions.)
>       Setup: Max:   1.280, Sum:  20.480, Balance:   1.000
>    Matching: Max:   1.164, Sum:  18.627, Balance:   1.000
> Contraction: Max:   0.649, Sum:  10.386, Balance:   1.000
>    InitPart: Max:   0.223, Sum:   3.563, Balance:   1.000
>     Project: Max:   0.015, Sum:   0.204, Balance:   1.179
>  Initialize: Max:   0.106, Sum:   1.667, Balance:   1.013
>       K-way: Max:   0.501, Sum:   8.019, Balance:   1.000
>       Remap: Max:   0.003, Sum:   0.044, Balance:   1.001
>       Total: Max:   3.940, Sum:  63.041, Balance:   1.000
> Fri Feb 03 11:29:05, Info:  Reading mesh. Done. 
> Fri Feb 03 11:29:05, Info:  Extracting fault information 
> Fri Feb 03 11:29:13, Info:  Mesh initialized in: 85.8047 (min: 85.8029, max: 85.8064)
> Fri Feb 03 11:29:16, Info:  Deriving clusters ids for min. time step width / multiRate: 6.01239e-05 / 2 
> Fri Feb 03 11:29:17, Info:  Number of elements in time clusters: 
> Fri Feb 03 11:29:17, Info:  0: 2 
> Fri Feb 03 11:29:17, Info:  1: 260 
> Fri Feb 03 11:29:17, Info:  2: 171410 
> Fri Feb 03 11:29:17, Info:  3: 4482859 
> Fri Feb 03 11:29:17, Info:  4: 3460705 
> Fri Feb 03 11:29:17, Info:  5: 950494 
> Fri Feb 03 11:29:17, Info:  6: 273921 
> Fri Feb 03 11:29:17, Info:  7: 2010916 
> Fri Feb 03 11:29:17, Info:  8: 926081 
> Fri Feb 03 11:29:17, Info:  9: 136 
> Fri Feb 03 11:29:17, Info:  maximum theoretical speedup (compared to GTS): 20.6495 per cell LTS, 14.0636 with the used clustering. 
> Fri Feb 03 11:29:17, Info:  Number of elements in dynamic rupture time clusters: 
> Fri Feb 03 11:29:17, Info:  0 (dr): 0 
> Fri Feb 03 11:29:17, Info:  1 (dr): 1 
> Fri Feb 03 11:29:17, Info:  2 (dr): 1910 
> Fri Feb 03 11:29:17, Info:  3 (dr): 140458 
> Fri Feb 03 11:29:17, Info:  4 (dr): 7077 
> Fri Feb 03 11:29:17, Info:  5 (dr): 0 
> Fri Feb 03 11:29:17, Info:  6 (dr): 0 
> Fri Feb 03 11:29:17, Info:  7 (dr): 0 
> Fri Feb 03 11:29:17, Info:  8 (dr): 0 
> Fri Feb 03 11:29:17, Info:  9 (dr): 0 
> Fri Feb 03 11:29:17, Info:  Initialize Friction Model 
> Rank:        0 | Info    | Synchronizing copy cell material data.
> Fri Feb 03 11:29:20, Info:  Enabling 2D fault output 
> Fri Feb 03 11:29:20, Info:  CPP: Initialising Fault output.  Number of sub-triangles:  4 
> Fri Feb 03 11:29:22, Info:  Initializing XDMF fault output. 
> Fri Feb 03 11:29:22, Info:  Fault writer thread affinity: "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5" 
> Fri Feb 03 11:29:23, Info:  Initializing XDMF fault output. Done. 
> Rank:        0 | Info    | Initializing element local matrices.
> Fri Feb 03 11:29:23, Info:  Initializing Fault, using a quadrature rule with  25  points. 
> 
> ===================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   RANK 3 PID 1673244 RUNNING AT i01r01c02s08
> =   KILLED BY SIGNAL: 11 (Segmentation fault)
> ===================================================================================

**Expected behavior**
Either a successful run or an error message providing a better explanation on what went wrong.

**To Reproduce**
Currently Loaded Modulefiles:
admin/1.0
tempdir/1.0
lrz/1.0
spack/22.2.1
intel-oneapi-compilers/2021.4.0
intel-mkl/2020
intel-mpi/2019-intel
gcc/11.2.0
cmake/3.21.4
python/3.8.11-extended
numactl/2.0.14-intel21
seissol-env/develop-intel21-impi-x2b
paraview/5.10.0-gcc11-impi

I tried both with `00bbf63e` and `b4d32e9d` (tag: v1.0.0-rc2).

Input files can be found in: **/hppfs/work/pn49ha/ru64lev2/Samos/dynamic**

**Additional context**
Different test have been conducted and the respective *.out files are in `/hppfs/scratch/09/ru64lev2/Samos_Fra_dyn_v1`.

I also ran test with `LtsWeightTypeID = 1`, which did not resolve the segmentation fault.
When using `tag: v1.0.0-rc2` I also tried to add `LtsWiggleFactorMin = 0.51`, `LtsWiggleFactorStepsize = 0.01` and `LtsWiggleFactorEnforceMaximumDifference = 1`, but then it takes ~11 min more to estimate the Wiggle Factors and the simulation still ends with a segmentation fault:

> Fri Feb 03 11:10:19, Info:  Welcome to SeisSol 
> Fri Feb 03 11:10:19, Info:  Copyright (c) 2012-2021, SeisSol Group 
> Fri Feb 03 11:10:19, Info:  Built on: Feb  3 2023 10:42:44 
> Fri Feb 03 11:10:19, Info:  Version: 202103_Sumatra-1310-gb4d32e9d 
> Fri Feb 03 11:10:19, Info:  Running on: i01r01c02s05 
> Fri Feb 03 11:10:19, Info:  Using MPI with #ranks: 16 
> Fri Feb 03 11:10:19, Info:  Using OMP with #threads/rank: 94 
> Fri Feb 03 11:10:19, Info:  OpenMP worker affinity (this process): "0123456789|0123456789|0123456789|0123456789|0123456-89|0123456789|0123456789|0123456789|0123456789|01234-" 
> Fri Feb 03 11:10:19, Info:  OpenMP worker affinity (this node)   : "0123456789|0123456789|0123456789|0123456789|0123456-89|0123456789|0123456789|0123456789|0123456789|01234-" 
> Fri Feb 03 11:10:19, Info:  Communication thread affinity        : "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5" 
> Fri Feb 03 11:10:19, Info:  The stack size ulimit is  2097152 [kb]. 
> Fri Feb 03 11:10:19, Info:  Input Parameters:
>  0x179a560 
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <                SeisSol MPI initialization               >
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    |  Double precision used for real.
> Rank:        0 | Info    | <--------------------------------------------------------->
>  INFORMATION: The assumed unit number is           6 for stdout and           0 
>  for stderr.
>               If no information follows, please change the value.
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <     Start ini_SeisSol ...                               >
> Rank:        0 | Info    | <--------------------------------------------------------->
> Rank:        0 | Info    | <  Parameters read from file: parameters_samos_noWL.par              >
> Rank:        0 | Info    | <                                                         >
> Rank:        0 | Info    | No plasticity assumed. 
> Rank:        0 | Info    | Use averaging to sample material values, when implemented.
> Rank:        0 | Info    | No attenuation assumed. 
> Rank:        0 | Info    | No adjoint wavefield generated. 
> Rank:        0 | Info    | Isotropic material is assumed. 
> Rank:        0 | Info    | Read a PUML mesh file
> Rank:        0 | Warning | Ignoring space order from parameter file, using           4
> Rank:        0 | Info    | Volume output is disabled
> Rank:        0 | Info    | Use HDF5 XdmfWriter backend
> Rank:        0 | Info    | Refinement for volume output is disabled
> Fri Feb 03 11:10:19, Info:  Running mini SeisSol to determine node weight 
> Fri Feb 03 11:10:19, Info:  Node weights: mean = 40.0448  std = 0.200888  min = 39.5743  median = 40.0778  max = 40.3063 
> Fri Feb 03 11:10:19, Info:  Reading PUML mesh mesh_noWL_Samos_Fra 
> Fri Feb 03 11:10:19, Info:  Found 12276784 cells 
> Fri Feb 03 11:10:19, Info:  Found 2403223 vertices 
> Fri Feb 03 11:10:36, Info:  Computing LTS weights. 
> Fri Feb 03 11:10:49, Info:  Baseline cost, without wiggle factor and cluster merging is 7.56638e+11 
> Fri Feb 03 11:22:01, Info:  Enforcing maximum difference when finding best wiggle factor took 2859426 reductions. 
> Fri Feb 03 11:22:01, Info:  The best wiggle factor after merging clusters is 0.63 with cost 7.28622e+11 
> Fri Feb 03 11:22:01, Info:  Cost decreased 3.70264 % with absolute cost difference 2.80156e+10 compared to the default wiggle factor of 1 
> Fri Feb 03 11:22:15, Info:  Limiting number of clusters to 2147483646 
> Fri Feb 03 11:22:15, Info:  Computing LTS weights. Done.  (42298 reductions.)
>       Setup: Max:   1.284, Sum:  20.548, Balance:   1.000
>    Matching: Max:   1.176, Sum:  18.810, Balance:   1.000
> Contraction: Max:   0.650, Sum:  10.400, Balance:   1.000
>    InitPart: Max:   0.228, Sum:   3.645, Balance:   1.000
>     Project: Max:   0.015, Sum:   0.207, Balance:   1.185
>  Initialize: Max:   0.105, Sum:   1.661, Balance:   1.012
>       K-way: Max:   0.518, Sum:   8.285, Balance:   1.000
>       Remap: Max:   0.003, Sum:   0.043, Balance:   1.001
>       Total: Max:   3.978, Sum:  63.652, Balance:   1.000
> Fri Feb 03 11:23:11, Info:  Reading mesh. Done. 
> Fri Feb 03 11:23:11, Info:  Extracting fault information 
> Fri Feb 03 11:23:12, Info:  Mesh initialized in: 773.105 (min: 773.104, max: 773.106)
> Fri Feb 03 11:23:36, Info:  Deriving clusters ids for min. time step width / multiRate: 4.20867e-05 / 2 
> Fri Feb 03 11:23:36, Info:  Due to wiggle factor of 0.63 the minimum timestep size is reduced to 2.65146e-05 
> Fri Feb 03 11:23:37, Info:  Number of elements in time clusters: 
> Fri Feb 03 11:23:37, Info:  0: 1 
> Fri Feb 03 11:23:37, Info:  1: 6 
> Fri Feb 03 11:23:37, Info:  2: 2876 
> Fri Feb 03 11:23:37, Info:  3: 732934 
> Fri Feb 03 11:23:37, Info:  4: 5547669 
> Fri Feb 03 11:23:37, Info:  5: 2240450 
> Fri Feb 03 11:23:37, Info:  6: 644111 
> Fri Feb 03 11:23:37, Info:  7: 211058 
> Fri Feb 03 11:23:37, Info:  8: 2309075 
> Fri Feb 03 11:23:37, Info:  9: 588604 
> Fri Feb 03 11:23:37, Info:  maximum theoretical speedup (compared to GTS): 20.6496 per cell LTS, 14.5666 with the used clustering. 
> Fri Feb 03 11:23:37, Info:  Number of elements in dynamic rupture time clusters: 
> Fri Feb 03 11:23:37, Info:  0 (dr): 0 
> Fri Feb 03 11:23:37, Info:  1 (dr): 0 
> Fri Feb 03 11:23:37, Info:  2 (dr): 17 
> Fri Feb 03 11:23:37, Info:  3 (dr): 18979 
> Fri Feb 03 11:23:37, Info:  4 (dr): 130322 
> Fri Feb 03 11:23:37, Info:  5 (dr): 16 
> Fri Feb 03 11:23:37, Info:  6 (dr): 0 
> Fri Feb 03 11:23:37, Info:  7 (dr): 0 
> Fri Feb 03 11:23:37, Info:  8 (dr): 0 
> Fri Feb 03 11:23:37, Info:  9 (dr): 0 
> Fri Feb 03 11:23:37, Info:  Initialize Friction Model 
> Rank:        0 | Info    | Synchronizing copy cell material data.
> Fri Feb 03 11:23:41, Info:  Enabling 2D fault output 
> Fri Feb 03 11:23:41, Info:  CPP: Initialising Fault output.  Number of sub-triangles:  4 
> Fri Feb 03 11:23:41, Info:  Initializing XDMF fault output. 
> Fri Feb 03 11:23:42, Info:  Fault writer thread affinity: "----------|----------|----------|----------|-------7--|----------|----------|----------|----------|-----5" 
> Rank:        0 | Info    | Initializing element local matrices.
> Fri Feb 03 11:23:43, Info:  Initializing XDMF fault output. Done. 
> Fri Feb 03 11:23:44, Info:  Initializing Fault, using a quadrature rule with  25  points. 
> 
> ===================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   RANK 8 PID 35293 RUNNING AT i01r01c03s01
> =   KILLED BY SIGNAL: 11 (Segmentation fault)
> ===================================================================================

My mesh is correct, as shown by `check_mesh`:

> Fri Feb 03 10:51:51, Info:  Read "/hppfs/work/pn49ha/ru64lev2/Samos/mesh/mesh_noWL_Samos_Fra" . 
> Fri Feb 03 10:51:51, Info:  Found 12276784 cells 
> Fri Feb 03 10:51:52, Info:  Found 2403223 vertices 
> Fri Feb 03 10:53:45, Info:  Mesh is correct 

(I also tried with a slightly different mesh which includes a water layer, but I got the same segmentation fault).

**Comment by Thomas-Ulrich** [comment] 2023-02-03 12:16
Running with /hppfs/work/pr45fi/di73yeq4/SeisSol/build/SeisSol_Debug_sskx_4_elastic I get
```
0 Fri Feb 03 13:13:59, Info:  Computing LTS weights.
0 Fri Feb 03 13:14:05, Info:  Limiting number of clusters to 2147483646
0 Fri Feb 03 13:14:05, Info:  Computing LTS weights. Done.  (44233 reductions.)
      Setup: Max:   0.728, Sum:  23.289, Balance:   1.000
   Matching: Max:   0.525, Sum:  16.799, Balance:   1.000
Contraction: Max:   0.358, Sum:  11.453, Balance:   1.000
   InitPart: Max:   0.214, Sum:   6.857, Balance:   1.000
    Project: Max:   0.009, Sum:   0.216, Balance:   1.363
 Initialize: Max:   0.080, Sum:   2.529, Balance:   1.010
      K-way: Max:   0.365, Sum:  11.693, Balance:   1.000
      Remap: Max:   0.002, Sum:   0.048, Balance:   1.001
      Total: Max:   2.280, Sum:  72.973, Balance:   1.000
SeisSol_Debug_sskx_4_elastic: /hppfs/work/pr45fi/di73yeq4/SeisSol/submodules/PUML/PUML.h:111: unsigned long PUML::Distributor::localToGlobalId(unsigned long, unsigned long): Assertion `localId < size' failed.
```
@sebwolf-de

**Comment by fabian-kutschera** [comment] 2023-02-03 14:42
I also generated a smaller mesh (~ 5Mio. elements) which can be found in the same folder.

**Comment by sebwolf-de** [comment] 2023-02-03 16:42
Thanks for reporting. If I change your `FunctionMap` with this `LuaMap`, the simulation starts successfully.
```
    components: !LuaMap
         returns: [T_s, T_d]
         function: |
             function f(x)
               ts = 0.
               td = -(x["mu_d"] * x["T_n"]) - x["Td0"]
               return {
                 T_s = ts,
                 T_d = td
               }
             end
```
I also see the assertion error in Debug mode, but it does not seem to interfere with the solution simulation.

**Comment by sebwolf-de** [comment] 2023-02-03 16:43
@fabian-kutschera. If the `LuaMap` indeed fixes your problem, please rename this issue to `PUML::Distributor::localToGlobalId(unsigned long, unsigned long): Assertion `localId < size' failed.`

**Comment by Thomas-Ulrich** [comment] 2023-02-06 09:42
Hi,

How did you find that the problem is here?
I It might be time to think about deprecating FunctionMap if that's the source of errors very difficult to track.

**Comment by sebwolf-de** [comment] 2023-02-06 10:02
* Some systematic debugging with ddt to find that the problem is located somewhere in the `ParameterDB`.
* Try a simple `ConstantMap` for all parameters. Since that "fixed" the problem, I knew that the problem came from the yaml file.
* Using a mixture of `ConstantMap` and Fabian's original yaml script to find, that the `FunctionMap` was the problem.
Tbh, I don't know why this function map breaks, it crashes the stack, so I can't really debug any further.

**Comment by sebwolf-de** [comment] 2023-02-06 10:45
See https://github.com/TUM-I5/PUML2/pull/8, for a solution of the failed assertion. I'll open a SeisSol PR, once the PUML PR is merged.

**Comment by sebwolf-de** [comment] 2023-02-06 10:56
The `FunctionMap` is not broken, it's just the fact, that  the line `T_s: 0;` should be replaced with `T_s: return 0;`

**Comment by Thomas-Ulrich** [comment] 2023-02-06 11:00
I see. I wonder if there is a way to catch the absence of a return statement.

**Comment by sebwolf-de** [comment] 2023-02-06 11:05
We could add something like
```
if (ss.str().find("return") == std::string::npos) {
  logError() << "Your FunctionMap does not contain a return statement.";
}
```

**Comment by krenzland** [comment] 2023-02-06 11:35
Or do the sane thing: Deprecate FunctionMap.

**Closed** 2023-02-07 09:19 UTC
Labels: bug
