### ISSUE TITLE
Segmentation Fault Error during Supermuc seissol run at  Initialize Friction Model step

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#751] opened 2022-12-06 13:23 UTC
### Discussed in https://github.com/SeisSol/SeisSol/discussions/742

<div type='discussions-op-text'>

<sup>Originally posted by **jwjeremy** November 25, 2022</sup>
**Describe the bug:**
Segmentation fault error encountered with running seissol in supermuc. The stout shows the segmentation error and the sterr is empty about the error. Please see the attached stout file.

The error is probably due to the mesh as previous mesh files work well with the parameter files and the rest of the settings. 

**Expected behavior:**
To be able to initialize the fault interface

**To Reproduce:**
The seissol setup and mesh files are in /hppfs/work/pn49ha/di75yik/TOHOKU_FL33
The Mesh can also be seen here. 
https://drive.google.com/drive/folders/1B0VY-Hh00t7bIJwGJN7zJ_Dd2Lv2IXdA?usp=sharing

[2461877.Tohoku_docker_test1.err.txt](https://github.com/SeisSol/SeisSol/files/10094820/2461877.Tohoku_docker_test1.err.txt)
[2461877.Tohoku_docker_test1.out.txt](https://github.com/SeisSol/SeisSol/files/10094821/2461877.Tohoku_docker_test1.out.txt)
</div>

**Comment by sebwolf-de** [comment] 2022-12-06 14:28
```
cp -r /hppfs/work/pn49ha/di75yik/TOHOKU_FL33 .
cp: cannot stat '/hppfs/work/pn49ha/di75yik/TOHOKU_FL33': Permission denied
``` 
Unfortunately, I don't have access to the folder...

**Comment by Thomas-Ulrich** [comment] 2022-12-07 10:55
He changed the permission and should have access now.
Here is what I get when running in Debug mode:
```
Wed Dec 07 11:53:59, Info:  Initialize Friction Model 
SeisSol_Debug_dskx_4_elastic: /hppfs/work/pr45fi/di73yeq4/SeisSol/src/Initializer/time_stepping/LtsLayout.h:213: unsigned int seissol::initializers::time_stepping::LtsLayout::getLocalClusterId(unsigned int): Assertion `l_clusterId < m_localClusters.size()' failed.
```

**Comment by sebwolf-de** [comment] 2022-12-08 12:42
I get the same error. It is not a problem with the dynamic rupture parts, but with the LTS setup. Just the first node is already ahead and prints the `Initialize Friction Model` message early. It doesn't work with `v0.9.0` either.

**Comment by sebwolf-de** [comment] 2022-12-08 17:31
I fear the mesh is broken:
`Element 2216102 , side 2  has a regular or DR boundary condition, but the neighborig element doesn't exist` 
I used this script to check the mesh: https://github.com/SeisSol/Meshing/pull/42

**Comment by sebwolf-de** [comment] 2022-12-09 08:10
I refined the tool a little bit, the problem is a "regular" face.

**Comment by Thomas-Ulrich** [comment] 2022-12-09 08:31
Well that's strange as I don't see any hole in the boundaries in the figure above.

**Comment by sebwolf-de** [comment] 2022-12-09 10:51
I don't know why you don't see the hole in the mesh.
```
Fri Dec 09 11:47:58, Info:  Element 0 , side 0  has a "regular" boundary condition, but the neighboring element doesn't exist
Fri Dec 09 11:47:58, Info:  Element 0 , side 2  has a "regular" boundary condition, but the neighboring element doesn't exist
```
The element `0` has these vertices:
```
array([[-299691.30091495, -521948.66873866, -305978.29296982],
       [-251228.02808731, -517570.66727225, -349577.08792755],
       [-303400.30405475, -574321.91213412, -349670.30655833],
       [-304166.15366487, -518050.21771685, -350891.15799103]])
```

**Comment by sebwolf-de** [comment] 2022-12-09 10:53
Actually, you don't see a hole in the mesh, because the boundaries are correct. The element `0` is in the middle of the mesh (all 4 sides are `regular`).

**Comment by Thomas-Ulrich** [comment] 2022-12-09 11:06
> Actually, you don't see a hole in the mesh, because the boundaries are correct. The element `0` is in the middle of the mesh (all 4 sides are `regular`). May I ask, how you generated this mesh?

ok, strange, I wonder which part of the meshing workflow can generate such a problem.

**Comment by sebwolf-de** [comment] 2022-12-12 12:49
Okay, the `Element 0` statement above is wrong, it should be:
```
Mon Dec 12 11:53:26, Info:  Element 626962 , side 0  has a "regular" boundary condition, but the neighboring element doesn't exist
Mon Dec 12 11:53:26, Info:  Element 626959 , side 2  has a "regular" boundary condition, but the neighboring element doesn't exist
```
with 
```
In [1]: import seissolxdmf as sx

In [2]: mesh = sx.seissolxdmf("MESH/Tohoku_v4_s2_202211_d15_LR_v3.xdmf")

In [3]: geom = mesh.ReadConnect()

In [4]: vertices = mesh.ReadGeometry()

In [5]: vertices[geom[ 626962 ]]
Out[5]:
array([[-4.36369539e+05, -4.95639709e+05, -9.40000000e+01],
       [-4.34345024e+05, -4.93416549e+05, -8.10000000e+01],
       [-4.34453221e+05, -4.95729526e+05, -2.80200000e+03],
       [-4.40138942e+05, -4.90314715e+05, -8.82053285e+01]])

In [6]: vertices[geom[ 626959 ]]
Out[6]:
array([[-4.37872653e+05, -4.99914432e+05, -1.23081749e+02],
       [-4.36369539e+05, -4.95639709e+05, -9.40000000e+01],
       [-4.34561360e+05, -4.98042500e+05, -1.11000000e+02],
       [-4.34453221e+05, -4.95729526e+05, -2.80200000e+03]])
```
These two tetrahedrons indeed are at the free surface, each with two faces at the free surface, but the `boundary` entry only flags one free surface each. If you zoom in close enough, you see the hole, when you've visualized the boundaries.
It can be fixed with
```
In [1]: import h5py

In [2]: f = h5py.File("MESH/Tohoku_v4_s2_202211_d15_LR_v3.puml.h5", 'r+')

In [3]: data = f["boundary"]

In [4]: data[626962] = 1 + 2**8

In [5]: data[626959] = 1 + 2**16

In [6]: f.close()
```
If I use the fixed mesh, I can start SeisSol successfully.

I am going to close the issue now, since the `Segmentation Fault Error` is fixed. Please feel free to open a new issue (probably at PUMGen), about why the mesh was not created correctly in the first place.

**Closed by sebwolf-de** 2022-12-12 12:49 UTC
